* gc-scraper
2018 April edition. A quick-and-dirty webscraper for LDS General Conference, using Pandoc to convert to orgmode files.

** Prerequisites
You will need [[https://github.com/technomancy/leiningen][Leiningen]] 2.0.0 or above installed.

You will also need [[http://pandoc.org/][Pandoc]] which is available free and also through linux repos. Pandoc performs the format conversion. 

The output will be [[https://orgmode.org/][emacs' orgmode]], which is included in emacs and supported by pandoc. Orgmode syntax functions like a fuller version of markdown (org is older, and not inherently compatible, although exporting to markdown is possible). 

** Running
Right now this can only be run from the REPL, like:

#+BEGIN_SRC clojure
gc-scraper.general-conference> (get-web-gc "my/slash/ending/output/directory/"
#+END_SRC

** TODO Improvements
- [ ] Clean up handling of references
- [ ] More robust output-dir handling
- [ ] Commandline Operability
- [ ] Allow specifying of different conference years or urls

** License
Copyright © 2018 Tory S. Anderson with the GPL v3 License. Use and modification is fine; attribution appreciated. 
